spring:
  application:
    name: config-rule-dev
  config:
    import: optional:configserver:http://ec2-3-39-24-149.ap-northeast-2.compute.amazonaws.com:8080
  jpa:
    hibernate:
      ddl-auto: create-drop

message:
  topic:
    name: "rule"
